const C = {
  // COUNTER
  COUNTER_INCREMENT: "COUNTER/INCREMENT",
  COUNTER_DECREMENT: "COUNTER/DECREMENT",
  COUNTER_REPLACE: "COUNTER/REPLACE",

  // THEME
  THEME_TOGGLE: "THEME/TOGGLE",
};

export default C;
